/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    jcenter()
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")
    testImplementation("org.mockito:mockito-inline:3.4.0")
    testImplementation("org.mockito:mockito-core:3.4.0")

    // This dependency is used by the application.

    compileOnly("org.projectlombok:lombok:1.18.16")
    annotationProcessor("org.projectlombok:lombok:1.18.16")

    compileOnly("org.slf4j:slf4j-log4j12:1.7.9")

    testCompileOnly("org.projectlombok:lombok:1.18.16")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.16")
    implementation("com.google.guava:guava:29.0-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("advent_of_code.PuzzleRunner")
}

tasks.withType<Test> {
    this.testLogging {
        this.showStandardStreams = true
    }
}